# Generated by Django 5.1.1 on 2024-09-30 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_interest'),
    ]

    operations = [
        migrations.CreateModel(
            name='Interested',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=15)),
                ('age', models.IntegerField()),
                ('starting_date', models.DateField()),
                ('address', models.CharField(blank=True, max_length=255)),
                ('session', models.CharField(choices=[('Early Morning', 'Early Morning'), ('Day', 'Day'), ('Night', 'Night')], max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Interest',
        ),
    ]
