# Generated by Django 5.1.1 on 2024-10-01 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0004_trainer_review'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trainers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('experience', models.IntegerField(help_text='Years of experience')),
                ('reg_no', models.CharField(max_length=50)),
                ('about', models.TextField()),
                ('photo', models.ImageField(upload_to='trainers/')),
            ],
        ),
        migrations.DeleteModel(
            name='Review',
        ),
        migrations.DeleteModel(
            name='Trainer',
        ),
    ]
